language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t deoneloff/docker-react -f Dockerfile.dev
script:
  - docker run -e CI=true deoneloff/docker-react npm run test -- --coverage
  
